# Generated by Django 5.2.4 on 2025-07-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('couleur', models.CharField(default='#1565C0', max_length=7)),
                ('icone', models.CharField(default='book', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document Word'), ('img', 'Image'), ('ppt', 'Présentation')], max_length=10)),
                ('auteur', models.CharField(default='Anonyme', max_length=100)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.matiere')),
            ],
            options={
                'ordering': ['-date_upload'],
                'indexes': [models.Index(fields=['-date_upload'], name='api_documen_date_up_a1064b_idx'), models.Index(fields=['matiere'], name='api_documen_matiere_618a5d_idx')],
            },
        ),
    ]
