# Generated by Django 5.2.4 on 2025-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250723_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='couleur',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
